config/routes.rb
Brimir::Application.routes.draw do

  get 'clubs/index'

  get 'clubs/new'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users
  resources :clubs

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new]

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :tickets, only: [ :index, :show ]
      resources :sessions, only: [ :create ]
    end
  end

end

app/models/user.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2015 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class User < ActiveRecord::Base
  devise Rails.application.config.devise_authentication_strategy, :recoverable,
    :rememberable, :trackable, :validatable,:omniauthable,
    omniauth_providers: [:google_oauth2]

  has_one :club_pres, :class_name => 'Club', :foreign_key => 'club_pres_id'
  has_many :assoc_pres, :class_name => 'Club', :foreign_key => 'assoc_pres_id'
  has_many :tickets, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :labelings, as: :labelable, dependent: :destroy
  has_many :labels, through: :labelings

  # identities for omniauth
  has_many :identities

  # All ldap users are agents by default, remove/comment this method if this
  # is not the intended behavior.
  def ldap_before_save
    self.agent = true
  end

  scope :agents, -> {
    where(agent: true)
  }

  scope :by_agent, ->(value) {
    where(agent: value)
  }

  scope :ordered, -> {
    order(:email)
  }

  scope :by_email, ->(email) {
    where('LOWER(email) LIKE ?', '%' + email.downcase + '%')
  }

  scope :search, ->(term) {
    if !term.nil?
      term.gsub!(/[\\%_]/) { |m| "!#{m}" }
      term = "%#{term.downcase}%"
      where('LOWER(email) LIKE ? ESCAPE ?', term, '!')
    end
  }

  def self.agents_to_notify
    User.agents
        .where(notify: true)
  end
end

app/controllers/users_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2015 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class UsersController < ApplicationController

  load_and_authorize_resource :user

  before_filter :load_locales, except: :index

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    # if no password was posted, remove from params
    if params[:user][:password] == ''
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if current_user == @user
      params[:user].delete(:agent) # prevent removing own agent permissions
    end

    if @user.update_attributes(user_params)

      if current_user.agent?
        redirect_to users_url, notice: I18n::translate(:settings_saved)
      else
        redirect_to tickets_url, notice: I18n::translate(:settings_saved)
      end

    else
      render action: 'edit'
    end
  end

  def index
    @users = User.ordered.paginate(page: params[:page])
    @users = @users.search(params[:q])
    @users = @users.by_agent(params[:agent] == '1') unless params[:agent].blank?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: I18n::translate(:user_added)
    else
      render 'new'
    end

  end

  private
    def load_locales
      @time_zones = ActiveSupport::TimeZone.all.map(&:name).sort
      @locales = []

      Dir.open("#{Rails.root}/config/locales").each do |file|
        unless ['.', '..'].include?(file)
          code = file[0...-4] # strip of .yml
          @locales << [I18n.translate(:language_name, locale: code), code]
        end
      end
    end

    def user_params
      attributes = params.require(:user).permit(
          :email,
          :password,
          :password_confirmation,
          :remember_me,
          :signature,
          :agent,
          :notify,
          :time_zone,
          :locale,
          :per_page,
          :prefer_plain_text,
          :added_by,
          :first_name,
          :last_name,
          label_ids: []
      )

      # prevent normal user and limited agent from changing email and role
      if !current_user.agent? || current_user.labelings.count > 0
        attributes.delete(:email)
        attributes.delete(:agent)
        attributes.delete(:label_ids)
      end

      return attributes
    end

end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'edit_user'} do |f| %>
    <div class="row mt mb">

      <div class="medium-6 columns">

        <h5><%= t(:account_settings) %></h5>

        <p><%= t(:only_fill_in_passwords_when_modifying) %></p>
        
         <%= f.text_field :first_name %>
         <%= f.text_field :last_name %>

        <% if can? :manage, User %>
            <%= f.text_field :email %>
        <% end %>

        <%= f.password_field :password %>

        <%= f.password_field :password_confirmation %>

        <div class="hide">

          <% if can? :manage, User %>
              <%= f.check_box :agent, label: t(:user_is_an_agent) %>
          <% end %>

          <%= f.select :time_zone, @time_zones %>

          <% @user.locale = 'en' if @user.locale.blank? # fallback on english  %>
          <%= f.select :locale, @locales %>

          <%= f.select :per_page, [10, 20, 30, 50, 75, 100] %>
        </div>
        
        <%= f.hidden_field :added_by, value: @current_user.id %>

      </div>

      <div class="medium-6 columns" style="display:none">
        <h5><%= t(:email_settings) %></h5>

        <%= f.check_box :prefer_plain_text %>

        <% if @user.agent? %>

          <%= f.check_box :notify,
              label: t(:receive_new_ticket_notifications) %>

          <%= f.text_area :signature, rows: 5, cols: 20, class: 'tinymce mbl' %>
        <% end %>

        <% if can? :create, Labeling.new(labelable: @user) %>
          <h5><%= t(:access_control) %></h5>

          <p><%= t(:have_access_to_label) %></p>

          <%= f.collection_select :label_ids, @labels, :id, :name, {}, {
              multiple: true, class: 'select2 mbl' } %>
        <% end %>

        <% unless Rails.application.secrets[:google_client_id].blank? %>

          <h5><%= t(:omniauth_connect_title) %></h5>

          <p><%= t(:omniauth_connect_text) %></p>

          <%= link_to user_omniauth_authorize_path(:google_oauth2) do %>
            <i class="fa fa-google-plus-square"></i>
            <%= t(:omniauth_connect_google_text) %>
          <% end %>

        <% end %>

      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns bt">
        <%= f.submit t(:save), class: 'success button radius mtl' %>
      </div>
    </div>

<% end %>

app/views/users/edit.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-12 columns">
      <h4 class="no-m pts pbs"><%= t(:edit_user) %></h4>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="panel pam no-bt">
  <div class="row collapse">
    <div class="medium-12 columns">
      <div class="row collapse">
        <div class="medium-3 columns">
          <h3 class="filter-title no-m pts plm"><%= t('My Club Presidents') %></h3>
        </div>
        <div class="medium-9 columns">
          <%= form_tag users_path, method: :get, class: 'prm' do %>

            <div class="row collapse">

              <%= link_to new_user_path, class: 'radius tiny button right mlm no-m' do %>
                <i class="fa fa-plus" style="top:1px"></i> Add new club president
              <% end %>

              <div class="hide">

                <div class="small-2 columns right">
                  <%= button_tag '<i class="fa fa-search"></i>'.html_safe, type: 'submit', class: 'secondary radius no-bl no-m button postfix' %>
                </div>
                <div class="small-5 columns right">
                  <%= text_field_tag :q, params[:q], class: 'no-m radius-tl radius-bl' %>
                </div>

                <label class="ib mts mll mrl pull-right"><%= radio_button_tag :agent, 0, params[:agent] == '0' %> <%= t(:customer) %></label>
                <label class="ib mts pull-right"><%= radio_button_tag :agent, 1, params[:agent] == '1' %> <%= t(:agent) %></label>
              </div>

            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table class="full">
  <thead>
    <tr>
      <th><%= t(:email) %></th>
      <th><%= t(:role) %></th>
      <th><%= t(:Club) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <% if user.added_by == @current_user.id %>
        <tr>
          <td>
            <%= user_avatar user, class: 'avatar' %>
            <%= link_to user.email, edit_user_path(user) %>
          </td>
          <td><%= (user.agent?) ? t(:agent) : t(:customer) %></td>
          <td>
            <% if user.club_pres == nil %>
              Not assigned to any club. Please go to the <%= link_to 'club page', clubs_path %> and assign one.
            <% else %>
              <%= user.club_pres.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="pagination-centered">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-12 columns">
      <h4 class="no-m pts pbs"><%= t(:new_user) %></h4>
    </div>
  </div>
</div>
<%= render 'form' %>