config/routes.rb
Brimir::Application.routes.draw do

  get 'clubs/index'

  get 'clubs/new'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users
  resources :clubs

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new]

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :tickets, only: [ :index, :show ]
      resources :sessions, only: [ :create ]
    end
  end

end

app/models/rule.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2015 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# filter rules applied to a ticket when it is created
class Rule < ActiveRecord::Base
  validates :filter_field, :filter_value, presence: true

  enum filter_operation: [:contains]
  enum action_operation: [:assign_label, :notify_user, :change_status,
                          :change_priority, :assign_user]

  def filter(ticket)

    if ticket.respond_to?(filter_field)
      value = ticket.send(filter_field)
    else
      value = ticket.attributes[filter_field]
    end

    value.include?(filter_value) if filter_operation == 'contains'
  end

  def execute(ticket)
    if action_operation == 'assign_label'
      label = Label.where(name: action_value).first_or_create
      ticket.labels << label

    elsif action_operation == 'notify_user'
      user = User.where(email: action_value).first

      ticket.notified_users << user unless user.nil?

    elsif action_operation == 'change_status'
      ticket.status = action_value.downcase
      ticket.save

    elsif action_operation == 'change_priority'
      ticket.priority = action_value.downcase
      ticket.save

    elsif action_operation == 'assign_user'
      user = User.where(email: action_value).first

      unless user.nil?
        ticket.assignee = user
        ticket.save
      end

    end
  end

  def self.apply_all(ticket)
    Rule.all.each do |rule|
      rule.execute(ticket) if rule.filter(ticket)
    end
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController

  load_and_authorize_resource :rule

  def index
    @rules = @rules.paginate(page: params[:page])
  end

  def new
  end

  def create
    @rule = Rule.new(rule_params)

    if @rule.save
      redirect_to rules_url, notice: t(:rule_added)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rule.update_attributes(rule_params)
      redirect_to rules_url, notice: t(:rule_modified)
    else
      render 'edit'
    end
  end

  def destroy
    @rule.destroy

    redirect_to rules_url, notice: t(:rule_deleted)
  end

  protected
    def rule_params
      params.require(:rule).permit(
          :filter_field,
          :filter_operation,
          :filter_value,
          :action_operation,
          :action_value,
      )
    end

end

app/views/rules/_form.html.erb
<%= form_for @rule do |f| %>
  <div class="row mt mb">
    <div class="large-6 columns">
      <%
        fields = []
        [:from, :subject, :content, :to].each do |key|
          fields << [t(key, scope: 'activerecord.attributes.ticket'), key]
        end
      %>
      <%= f.select(:filter_field, fields) %>

      <%= f.collection_select(:filter_operation, t('activerecord.attributes.rule.filter_operations'), :first, :last) %>

      <%= f.text_field :filter_value %>

      <%= f.collection_select(:action_operation, t('activerecord.attributes.rule.action_operations'), :first, :last) %>

      <%= f.text_field :action_value %>
    </div>
  </div>

  <div class="row">
    <div class="medium-12 columns bt">
      <%= f.submit t(:save), class: 'success button radius mtl' %>
    </div>
  </div>
<% end %>

app/views/rules/edit.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-6 columns">
      <h4 class="no-m pts pbs"><%= t(:edit_rule) %></h4>
    </div>
    <div class="medium-6 columns">
      <%= link_to t(:delete_rule), rule_path(@rule), 
          method: :delete, 
          data: { confirm: t(:are_you_sure) },
          class: 'no-m radius right tiny button' %>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/rules/index.html.erb
<div class="panel no-bt">
  <div class="row collapse">
    <div class="medium-6 columns">
      <h4 class="no-m pts pbs"><%= t(:rules) %></h4>
    </div>
    <div class="medium-6 columns">
      <%= link_to t(:new_rule), new_rule_path, class: 'no-m tiny button right radius' %>
    </div>
  </div>
</div>

<div class="row collapse">
  <div class="large-12 columns">

    <table class="full">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.rule.filter_field') %></th>
          <th><%= t('activerecord.attributes.rule.filter_operation') %></th>
          <th><%= t('activerecord.attributes.rule.filter_value') %></th>
          <th><%= t('activerecord.attributes.rule.action_operation') %></th>
          <th><%= t('activerecord.attributes.rule.action_value') %></th>
        </tr>
      </thead>
      <tbody>
        <% @rules.each do |rule| %>
          <tr>
            <td><%= link_to t(rule.filter_field, scope: 'activerecord.attributes.ticket'), edit_rule_path(rule) %></td>
            <td><%= t(rule.filter_operation, scope: 'activerecord.attributes.rule.filter_operations') %></td>
            <td><%= rule.filter_value %></td>
            <td><%= t(rule.action_operation, scope: 'activerecord.attributes.rule.action_operations') %></td>
            <td><%= rule.action_value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination-centered">
      <%= will_paginate @rules %>
    </div>
  </div>
</div>

app/views/rules/new.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-12 columns">
      <h4 class="no-m pts pbs"><%= t(:new_rule) %></h4>
    </div>
  </div>
</div>
<%= render 'form' %>